export interface PaymentData {
  id?: string;           // optional if generated by backend
  amount: number;
  method: string;
  status: "pending" | "success" | "failed";
  userId: string;
  date?: string;         // optional
}

export interface School {
  _id: string;
  name: string;
  email: string;
}
